require "active_support/core_ext/integer/time"

Rails.application.configure do
  # Settings specified here will take precedence over those in config/application.rb.

  # Make code changes take effect immediately without server restart.
  config.enable_reloading = true

  # Do not eager load code on boot.
  config.eager_load = false

  # Configure file watcher for Docker volumes
  # Use polling mode for better compatibility with Docker volumes on Linux
  # This is set via environment variable in docker-compose.yml
  # If auto-reload still doesn't work, ensure LISTEN_GEM_USE_POLLING=true is set

  # Show full error reports.
  config.consider_all_requests_local = true

  # Enable server timing.
  config.server_timing = true

  # Enable/disable Action Controller caching. By default Action Controller caching is disabled.
  # Run rails dev:cache to toggle Action Controller caching.
  if Rails.root.join("tmp/caching-dev.txt").exist?
    config.action_controller.perform_caching = true
    config.action_controller.enable_fragment_cache_logging = true
    config.public_file_server.headers = { "cache-control" => "public, max-age=#{2.days.to_i}" }
  else
    config.action_controller.perform_caching = false
  end

  # Change to :null_store to avoid any caching.
  config.cache_store = :memory_store

  # Store uploaded files on S3-compatible storage (SeaweedFS) - see config/storage.yml.
  config.active_storage.service = :s3

  # Don't care if the mailer can't send.
  config.action_mailer.raise_delivery_errors = true

  # Make template changes take effect immediately.
  config.action_mailer.perform_caching = false

  # Set URL to be used by links generated in mailer templates.
  # Utiliser l'URL publique pour que les liens fonctionnent dans les emails reçus
  config.action_mailer.default_url_options = {
    host: ENV.fetch("MAILER_HOST", "dev-grenoble-roller.flowtech-lab.org"),
    protocol: ENV.fetch("MAILER_PROTOCOL", "https")
  }

  # En développement, vous pouvez choisir entre :
  # Option 1: Stocker les emails dans des fichiers (par défaut)
  # config.action_mailer.delivery_method = :file
  # config.action_mailer.file_settings = { location: Rails.root.join("tmp/mails") }

  # Option 2: Envoyer de vrais emails par SMTP (actif)
  config.action_mailer.delivery_method = :smtp
  config.action_mailer.smtp_settings = {
    user_name: Rails.application.credentials.dig(:smtp, :user_name),
    password: Rails.application.credentials.dig(:smtp, :password),
    address: Rails.application.credentials.dig(:smtp, :address) || "smtp.ionos.fr",
    port: Rails.application.credentials.dig(:smtp, :port) || 465,
    domain: Rails.application.credentials.dig(:smtp, :domain) || "grenoble-roller.org",
    authentication: :plain,
    enable_starttls_auto: false,
    ssl: true,
    openssl_verify_mode: "peer"
  }

  # Print deprecation notices to the Rails logger.
  config.active_support.deprecation = :log

  # Raise an error on page load if there are pending migrations.
  config.active_record.migration_error = :page_load

  # Highlight code that triggered database queries in logs.
  config.active_record.verbose_query_logs = true

  # Append comments with runtime information tags to SQL queries in logs.
  config.active_record.query_log_tags_enabled = true

  # Highlight code that enqueued background job in logs.
  config.active_job.verbose_enqueue_logs = true

  # Use Solid Queue as the queuing backend for Active Job (en développement aussi)
  # Solid Queue utilise PostgreSQL (même base que l'application)
  config.active_job.queue_adapter = :solid_queue

  # Bullet gem configuration for N+1 query detection
  config.after_initialize do
    require "bullet"
    Bullet.enable = true
    Bullet.alert = true
    Bullet.bullet_logger = true
    Bullet.console = true
    Bullet.rails_logger = true
    Bullet.add_footer = true
  rescue LoadError
    # Bullet not available (not in Gemfile or bundle install not run)
  end

  # Highlight code that triggered redirect in logs.
  config.action_dispatch.verbose_redirect_logs = true

  # Suppress logger output for asset requests.
  config.assets.quiet = true

  # Raises error for missing translations.
  # config.i18n.raise_on_missing_translations = true

  # Annotate rendered view with file names.
  config.action_view.annotate_rendered_view_with_filenames = true

  # Uncomment if you wish to allow Action Cable access from any origin.
  # config.action_cable.disable_request_forgery_protection = true

  # Raise error when a before_action's only/except options reference missing actions.
  config.action_controller.raise_on_missing_callback_actions = true

  # Apply autocorrection by RuboCop to files generated by `bin/rails generate`.
  # config.generators.apply_rubocop_autocorrect_after_generate!

  # In development, allow all hosts to avoid 403 errors with reverse proxies
  # This is safe because development is not exposed to the internet
  # HAProxy/pfSense healthchecks and local network access will work without issues
  config.hosts.clear
  config.host_authorization = {
    exclude: ->(request) { true }  # Allow all hosts in development
  }
end
